from __future__ import annotations

import importlib.util
import json
import math
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, Callable

from jinja2 import Environment, PackageLoader, select_autoescape

from agent_buffet.config import AgentConfig, load_config


Move = list[Any]


@dataclass
class Planet:
    id: int
    x: float
    y: float
    owner: int
    ships: int
    production: int
    angle: float
    orbit_radius: float
    angular_velocity: float


@dataclass
class Fleet:
    owner: int
    source: int
    target: int
    ships: int
    angle: float
    eta: int
    sun_risk: bool


class OrbitWarsAdapter:
    competition = "orbit-wars"

    def __init__(self) -> None:
        self.jinja = Environment(
            loader=PackageLoader("agent_buffet.orbit_wars", "templates"),
            autoescape=select_autoescape(enabled_extensions=()),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def render_agent(self, config_path: Path, output_dir: Path) -> dict[str, Path]:
        config = load_config(config_path)
        template_name = "simple_sniper.py.j2" if config.base_template == "simple_sniper" else "advanced_modular.py.j2"
        output_dir.mkdir(parents=True, exist_ok=True)
        main_path = output_dir / "main.py"
        readme_path = output_dir / "README.md"
        report_path = output_dir / "report.md"

        rendered = self.jinja.get_template(template_name).render(config=config.model_dump(mode="json"))
        main_path.write_text(rendered, encoding="utf-8")
        readme_path.write_text(self._render_readme(config), encoding="utf-8")
        report_path.write_text(self._render_build_report(config), encoding="utf-8")
        return {"main": main_path, "readme": readme_path, "report": report_path}

    def _render_readme(self, config: AgentConfig) -> str:
        return "\n".join(
            [
                f"# {config.name}",
                "",
                "Generated by Agent Buffet for Orbit Wars.",
                "",
                "## Strategy",
                "",
                f"- Expansion: {config.strategy.expansion}",
                f"- Aggression: {config.strategy.aggression}",
                f"- Defense: {config.strategy.defense}",
                f"- Comets: {config.strategy.comet_usage}",
                f"- Endgame swarm: {config.strategy.endgame_swarm}",
                "",
                "## Safety",
                "",
                f"- Sun avoidance: {config.physics.sun_avoidance}",
                f"- Moving-planet prediction: {config.physics.moving_planet_prediction}",
                f"- Incoming fleet defense: {config.defense.detect_incoming_fleets}",
                "",
            ]
        )

    def _render_build_report(self, config: AgentConfig) -> str:
        risks = []
        if not config.physics.sun_avoidance:
            risks.append("Sun collision guard is disabled.")
        if config.strategy.comet_usage == "off":
            risks.append("Comets are ignored.")
        if not config.defense.reinforce_under_attack:
            risks.append("Owned planets are not reinforced when threatened.")
        if not risks:
            risks.append("Main remaining risk is local simulator mismatch with the official environment.")
        return "\n".join(
            [
                f"# Build Report: {config.name}",
                "",
                f"Template: `{config.base_template}`",
                "",
                "## What It Does",
                "",
                f"- Uses a {config.strategy.expansion} expansion posture.",
                f"- Uses {config.strategy.aggression} aggression against enemy planets.",
                f"- Reserves ships according to a {config.strategy.defense} defense posture.",
                f"- Scores targets with distance, production, capture cost, and ETA terms.",
                f"- Predicts moving planets up to {config.physics.max_prediction_ticks} turns ahead.",
                "",
                "## Main Risks",
                "",
                *[f"- {risk}" for risk in risks],
                "",
            ]
        )

    def load_agent(self, path: Path) -> Callable[[Any], Any]:
        spec = importlib.util.spec_from_file_location(f"agent_buffet_candidate_{abs(hash(path))}", path)
        if spec is None or spec.loader is None:
            raise ValueError(f"Could not import {path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return _find_agent_callable(module)

    def validate_agent(self, path: Path) -> tuple[bool, list[str], dict[str, Any]]:
        errors: list[str] = []
        details: dict[str, Any] = {}
        try:
            agent = self.load_agent(path)
        except Exception as exc:
            return False, [f"Import failed: {exc}"], details

        obs = sample_observation(seed=7, player=1)
        started = time.perf_counter()
        try:
            moves = agent(obs)
        except Exception as exc:
            return False, [f"agent(obs) raised: {type(exc).__name__}: {exc}"], details
        elapsed_ms = (time.perf_counter() - started) * 1000
        details["runtime_ms"] = round(elapsed_ms, 3)
        details["moves"] = moves
        errors.extend(validate_moves(moves, obs, elapsed_ms=elapsed_ms))
        return not errors, errors, details

    def run_suite(self, agent_path: Path, opponents: list[str], games: int, turns: int = 220) -> dict[str, Any]:
        agent = self.load_agent(agent_path)
        aggregate = _empty_metrics()
        per_opponent: dict[str, Any] = {}
        games_per_opponent = max(1, math.ceil(games / max(1, len(opponents))))
        total_games = 0
        for opponent in opponents:
            opp_metrics = _empty_metrics()
            for seed_offset in range(games_per_opponent):
                if total_games >= games:
                    break
                seed = 1000 + total_games * 37 + seed_offset
                result = run_match(agent, opponent, seed=seed, turns=turns)
                _accumulate(aggregate, result)
                _accumulate(opp_metrics, result)
                total_games += 1
            per_opponent[opponent] = _finalize(opp_metrics)
        final = _finalize(aggregate)
        final["games"] = total_games
        final["per_opponent"] = per_opponent
        return final


def _find_agent_callable(module: ModuleType) -> Callable[[Any], Any]:
    for name in ("agent", "act"):
        value = getattr(module, name, None)
        if callable(value):
            return value
    raise ValueError("File must define callable agent(obs) or act(obs)")


def sample_observation(seed: int = 0, player: int = 1) -> dict[str, Any]:
    rng = random.Random(seed)
    planets = []
    for pid in range(8):
        angle = (math.tau / 8) * pid + rng.uniform(-0.1, 0.1)
        radius = 35 + (pid % 4) * 16
        owner = 0
        if pid == 0:
            owner = player
        elif pid == 4:
            owner = 2 if player == 1 else 1
        planets.append(
            {
                "id": pid,
                "x": math.cos(angle) * radius,
                "y": math.sin(angle) * radius,
                "owner": owner,
                "ships": 45 if owner else rng.randint(8, 24),
                "production": rng.randint(1, 5),
                "angle": angle,
                "orbit_radius": radius,
                "angular_velocity": 0.012 * (-1 if pid % 2 else 1),
            }
        )
    return {
        "player": player,
        "step": 0,
        "total_steps": 220,
        "remainingOverageTime": 60,
        "angular_velocity": 0.012,
        "planets": planets,
        "fleets": [],
        "comets": [],
        "comet_ids": [],
    }


def validate_moves(moves: Any, obs: dict[str, Any], *, elapsed_ms: float = 0.0, act_timeout_ms: float = 800.0) -> list[str]:
    errors: list[str] = []
    if elapsed_ms > act_timeout_ms:
        errors.append(f"Runtime {elapsed_ms:.1f}ms exceeds local threshold {act_timeout_ms:.1f}ms")
    if not isinstance(moves, list):
        return ["agent(obs) must return a list"]
    player = int(obs.get("player", obs.get("player_id", 1)))
    planets = {int(p["id"]): p for p in obs.get("planets", [])}
    owned = {pid: int(p.get("ships", 0)) for pid, p in planets.items() if int(p.get("owner", 0)) == player}
    spent: dict[int, int] = {}
    for index, move in enumerate(moves):
        if not isinstance(move, (list, tuple)) or len(move) != 3:
            errors.append(f"Move {index} must have exactly 3 fields")
            continue
        from_id, angle, ships = move
        try:
            from_id = int(from_id)
            angle = float(angle)
            ships = int(ships)
        except (TypeError, ValueError):
            errors.append(f"Move {index} has non-numeric fields")
            continue
        if from_id not in owned:
            errors.append(f"Move {index} sends from unowned planet {from_id}")
        if not math.isfinite(angle):
            errors.append(f"Move {index} angle is not finite")
        if ships <= 0:
            errors.append(f"Move {index} ships must be positive")
        spent[from_id] = spent.get(from_id, 0) + ships
        if spent[from_id] > owned.get(from_id, 0):
            errors.append(f"Move {index} overspends planet {from_id}: {spent[from_id]} > {owned.get(from_id, 0)}")
    return errors


def run_match(agent: Callable[[Any], Any], opponent: str, *, seed: int, turns: int = 220) -> dict[str, Any]:
    rng = random.Random(seed)
    planets = _initial_planets(rng)
    fleets: list[Fleet] = []
    metrics = _empty_metrics()
    opponent_agent = _opponent_agent(opponent)
    eliminated_turn: int | None = None

    for step in range(turns):
        _produce(planets)
        _move_planets(planets)
        for player, controller in [(1, agent), (2, opponent_agent)]:
            obs = _observation_from_state(planets, fleets, player, step, turns)
            started = time.perf_counter()
            try:
                moves = controller(obs)
            except Exception:
                moves = []
                if player == 1:
                    metrics["timeout_turns"] += 1
            elapsed_ms = (time.perf_counter() - started) * 1000
            move_errors = validate_moves(moves, obs, elapsed_ms=elapsed_ms)
            if move_errors:
                if player == 1:
                    metrics["invalid_moves"] += len(move_errors)
                moves = _filter_valid_moves(moves, obs)
            spawned, sun_losses = _spawn_fleets(planets, moves, player)
            fleets.extend(spawned)
            if player == 1:
                metrics["fleets_lost_to_sun"] += sun_losses
                metrics["fleets_sent"] += len(spawned)
        _advance_fleets(planets, fleets, metrics)
        if not any(p.owner == 1 for p in planets):
            eliminated_turn = step
            break

    player_score = sum(p.ships for p in planets if p.owner == 1) + sum(f.ships for f in fleets if f.owner == 1)
    opponent_score = sum(p.ships for p in planets if p.owner == 2) + sum(f.ships for f in fleets if f.owner == 2)
    player_planets = sum(1 for p in planets if p.owner == 1)
    opponent_planets = sum(1 for p in planets if p.owner == 2)
    metrics["wins"] += int(player_score > opponent_score)
    metrics["losses"] += int(player_score <= opponent_score)
    metrics["final_ship_score"] += player_score
    metrics["final_ship_diff"] += player_score - opponent_score
    metrics["planet_count"] += player_planets
    metrics["production_controlled"] += sum(p.production for p in planets if p.owner == 1)
    metrics["eliminations"] += int(eliminated_turn is not None)
    metrics["turn_of_elimination"] += eliminated_turn or turns
    metrics["neutral_captures_by_50"] += metrics.pop("_neutral_captures_by_50", 0)
    metrics["enemy_planets_captured"] += metrics.pop("_enemy_captures", 0)
    metrics["high_production_planets_captured"] += metrics.pop("_high_prod_captures", 0)
    metrics["games"] = 1
    metrics["_opponent_planets"] = opponent_planets
    return metrics


def _initial_planets(rng: random.Random) -> list[Planet]:
    planets: list[Planet] = []
    for pid in range(12):
        angle = math.tau * pid / 12
        radius = 30 + (pid % 4) * 17
        owner = 0
        ships = rng.randint(10, 28)
        if pid == 0:
            owner = 1
            ships = 58
        elif pid == 6:
            owner = 2
            ships = 58
        planets.append(
            Planet(
                id=pid,
                x=math.cos(angle) * radius,
                y=math.sin(angle) * radius,
                owner=owner,
                ships=ships,
                production=rng.randint(1, 6),
                angle=angle,
                orbit_radius=radius,
                angular_velocity=0.006 + (pid % 5) * 0.002 * (-1 if pid % 2 else 1),
            )
        )
    return planets


def _produce(planets: list[Planet]) -> None:
    for p in planets:
        if p.owner:
            p.ships += p.production


def _move_planets(planets: list[Planet]) -> None:
    for p in planets:
        p.angle += p.angular_velocity
        p.x = math.cos(p.angle) * p.orbit_radius
        p.y = math.sin(p.angle) * p.orbit_radius


def _observation_from_state(planets: list[Planet], fleets: list[Fleet], player: int, step: int, turns: int) -> dict[str, Any]:
    return {
        "player": player,
        "step": step,
        "total_steps": turns,
        "remainingOverageTime": 60,
        "angular_velocity": 0.01,
        "planets": [asdict(p) for p in planets],
        "fleets": [asdict(f) for f in fleets],
        "comets": [],
        "comet_ids": [],
    }


def _filter_valid_moves(moves: Any, obs: dict[str, Any]) -> list[Move]:
    if not isinstance(moves, list):
        return []
    valid = []
    player = obs.get("player", 1)
    owned = {int(p["id"]): int(p["ships"]) for p in obs.get("planets", []) if int(p.get("owner", 0)) == player}
    spent: dict[int, int] = {}
    for move in moves:
        if not isinstance(move, (list, tuple)) or len(move) != 3:
            continue
        try:
            source, angle, ships = int(move[0]), float(move[1]), int(move[2])
        except (TypeError, ValueError):
            continue
        if source not in owned or ships <= 0 or not math.isfinite(angle):
            continue
        spent[source] = spent.get(source, 0) + ships
        if spent[source] <= owned[source]:
            valid.append([source, angle, ships])
    return valid


def _spawn_fleets(planets: list[Planet], moves: list[Move], owner: int) -> tuple[list[Fleet], int]:
    by_id = {p.id: p for p in planets}
    spawned: list[Fleet] = []
    sun_losses = 0
    for source_id, angle, ships in moves:
        source = by_id.get(int(source_id))
        if source is None or source.owner != owner or source.ships < int(ships):
            continue
        target = _target_for_angle(source, planets, float(angle))
        if target is None:
            continue
        source.ships -= int(ships)
        dist = math.dist((source.x, source.y), (target.x, target.y))
        risk = _ray_hits_sun(source.x, source.y, float(angle), dist)
        if risk and int(ships) >= 10:
            sun_losses += 1
            continue
        speed = max(1.5, 9.0 / math.sqrt(max(1, int(ships))))
        eta = max(1, int(math.ceil(dist / speed)))
        spawned.append(Fleet(owner=owner, source=source.id, target=target.id, ships=int(ships), angle=float(angle), eta=eta, sun_risk=risk))
    return spawned, sun_losses


def _target_for_angle(source: Planet, planets: list[Planet], angle: float) -> Planet | None:
    best: tuple[float, Planet] | None = None
    for p in planets:
        if p.id == source.id:
            continue
        target_angle = math.atan2(p.y - source.y, p.x - source.x)
        diff = abs(math.atan2(math.sin(target_angle - angle), math.cos(target_angle - angle)))
        score = diff + 0.002 * math.dist((source.x, source.y), (p.x, p.y))
        if best is None or score < best[0]:
            best = (score, p)
    return best[1] if best else None


def _segment_hits_sun(x1: float, y1: float, x2: float, y2: float, radius: float = 12.0) -> bool:
    dx = x2 - x1
    dy = y2 - y1
    denom = dx * dx + dy * dy
    if denom == 0:
        return False
    t = max(0.0, min(1.0, -(x1 * dx + y1 * dy) / denom))
    closest_x = x1 + t * dx
    closest_y = y1 + t * dy
    return math.hypot(closest_x, closest_y) <= radius


def _ray_hits_sun(x: float, y: float, angle: float, max_distance: float, radius: float = 12.0) -> bool:
    dx = math.cos(angle)
    dy = math.sin(angle)
    t = -(x * dx + y * dy)
    if t < 0 or t > max_distance:
        return False
    closest_x = x + t * dx
    closest_y = y + t * dy
    return math.hypot(closest_x, closest_y) <= radius


def _advance_fleets(planets: list[Planet], fleets: list[Fleet], metrics: dict[str, Any]) -> None:
    by_id = {p.id: p for p in planets}
    remaining: list[Fleet] = []
    for fleet in fleets:
        fleet.eta -= 1
        if fleet.eta > 0:
            remaining.append(fleet)
            continue
        target = by_id.get(fleet.target)
        if target is None:
            continue
        if target.owner == fleet.owner:
            target.ships += fleet.ships
            metrics["reinforcements_sent"] += 1
        elif fleet.ships > target.ships:
            previous_owner = target.owner
            target.owner = fleet.owner
            target.ships = fleet.ships - target.ships
            if fleet.owner == 1 and previous_owner == 0:
                metrics["_neutral_captures_by_50"] += 1
            if fleet.owner == 1 and previous_owner == 2:
                metrics["_enemy_captures"] += 1
            if fleet.owner == 1 and target.production >= 5:
                metrics["_high_prod_captures"] += 1
        else:
            if fleet.ships <= target.ships:
                metrics["attacks_arrived_underpowered"] += int(fleet.owner == 1)
            target.ships -= fleet.ships
    fleets[:] = remaining


def _opponent_agent(name: str) -> Callable[[Any], Any]:
    if name in {"random", "starter_sniper", "safe_sniper", "previous_champion", "self_play"}:
        return lambda obs: _builtin_agent(obs, name)
    return lambda obs: _builtin_agent(obs, "starter_sniper")


def _builtin_agent(obs: dict[str, Any], style: str) -> list[Move]:
    player = int(obs.get("player", 1))
    planets = obs.get("planets", [])
    owned = [p for p in planets if int(p.get("owner", 0)) == player and int(p.get("ships", 0)) > 12]
    targets = [p for p in planets if int(p.get("owner", 0)) != player]
    moves: list[Move] = []
    for source in owned[: 1 if style == "starter_sniper" else 3]:
        if not targets:
            continue
        if style == "random":
            target = random.choice(targets)
        elif style in {"safe_sniper", "previous_champion"}:
            target = min(targets, key=lambda p: (abs(int(p.get("ships", 0)) - int(p.get("production", 1)) * 3), _dist(source, p)))
        else:
            target = min(targets, key=lambda p: _dist(source, p))
        ships = max(1, min(int(source.get("ships", 0)) - 6, int(target.get("ships", 0)) + 3))
        moves.append([int(source["id"]), math.atan2(float(target["y"]) - float(source["y"]), float(target["x"]) - float(source["x"])), ships])
    return moves


def _dist(a: dict[str, Any], b: dict[str, Any]) -> float:
    return math.dist((float(a["x"]), float(a["y"])), (float(b["x"]), float(b["y"])))


def _empty_metrics() -> dict[str, Any]:
    return {
        "games": 0,
        "wins": 0,
        "losses": 0,
        "final_ship_score": 0.0,
        "final_ship_diff": 0.0,
        "planet_count": 0.0,
        "production_controlled": 0.0,
        "eliminations": 0,
        "turn_of_elimination": 0.0,
        "invalid_moves": 0,
        "timeout_turns": 0,
        "fleets_lost_to_sun": 0,
        "fleets_sent": 0,
        "attacks_arrived_underpowered": 0,
        "duplicate_attacks": 0,
        "neutral_captures_by_50": 0,
        "enemy_planets_captured": 0,
        "high_production_planets_captured": 0,
        "reinforcements_sent": 0,
        "comets_captured": 0,
        "_neutral_captures_by_50": 0,
        "_enemy_captures": 0,
        "_high_prod_captures": 0,
    }


def _accumulate(target: dict[str, Any], result: dict[str, Any]) -> None:
    for key, value in result.items():
        if key.startswith("_"):
            continue
        target[key] = target.get(key, 0) + value


def _finalize(metrics: dict[str, Any]) -> dict[str, Any]:
    games = max(1, int(metrics.get("games", 0)))
    averaged = dict(metrics)
    for key in [
        "final_ship_score",
        "final_ship_diff",
        "planet_count",
        "production_controlled",
        "turn_of_elimination",
        "invalid_moves",
        "timeout_turns",
        "fleets_lost_to_sun",
        "fleets_sent",
        "attacks_arrived_underpowered",
        "neutral_captures_by_50",
        "enemy_planets_captured",
        "high_production_planets_captured",
        "reinforcements_sent",
        "comets_captured",
    ]:
        averaged[f"avg_{key}"] = round(float(metrics.get(key, 0)) / games, 3)
    averaged["win_rate"] = round(float(metrics.get("wins", 0)) / games, 3)
    averaged["elimination_rate"] = round(float(metrics.get("eliminations", 0)) / games, 3)
    for key in list(averaged):
        if key.startswith("_"):
            averaged.pop(key, None)
    return averaged


def save_metrics(path: Path, metrics: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metrics, indent=2, sort_keys=True), encoding="utf-8")
